// Generated by scripts/rebuild_pink_stage_layers.py. Do not edit by hand.

export interface PinkStageProp {
  id: number;
  file: string;
  x: number;
  y: number;
  width: number;
  height: number;
  visibleBottom: number;
}

export const PINK_STAGE_SOURCE_WIDTH = 1920;
export const PINK_STAGE_SOURCE_HEIGHT = 1080;

export const PINK_STAGE_PROPS: readonly PinkStageProp[] = [
  { id: 1, file: 'object-01-foliage-strip-left.png', x: 39, y: 0, width: 129, height: 171, visibleBottom: 139 },
  { id: 2, file: 'object-02-tree-cluster-left.png', x: 124, y: 0, width: 132, height: 203, visibleBottom: 200 },
  { id: 3, file: 'object-03-foliage-column-left.png', x: 419, y: 0, width: 142, height: 251, visibleBottom: 231 },
  { id: 4, file: 'object-04-foliage-column-right.png', x: 1348, y: 0, width: 145, height: 149, visibleBottom: 112 },
  { id: 5, file: 'object-05-frog-totem-booth.png', x: 1449, y: 0, width: 165, height: 336, visibleBottom: 304 },
  { id: 6, file: 'object-06-canopy-foliage-right.png', x: 1568, y: 0, width: 177, height: 111, visibleBottom: 109 },
  { id: 9, file: 'object-09-hanging-sign-right.png', x: 1740, y: 0, width: 149, height: 263, visibleBottom: 231 },
  { id: 10, file: 'object-10-edge-pillar-right.png', x: 1854, y: 0, width: 66, height: 256, visibleBottom: 238 },
  { id: 11, file: 'object-11-entrance-gate.png', x: 613, y: 0, width: 653, height: 350, visibleBottom: 332 },
  { id: 12, file: 'object-12-entrance-pillar-left.png', x: 523, y: 0, width: 192, height: 323, visibleBottom: 295 },
  { id: 15, file: 'object-15-entrance-pillar-right.png', x: 1189, y: 0, width: 193, height: 325, visibleBottom: 325 },
  { id: 16, file: 'object-16-edge-foliage-left.png', x: 0, y: 0, width: 75, height: 164, visibleBottom: 130 },
  { id: 17, file: 'object-17-vending-stack-left.png', x: 298, y: 0, width: 196, height: 285, visibleBottom: 266 },
  { id: 18, file: 'object-18-small-robed-statue.png', x: 1570, y: 34, width: 120, height: 241, visibleBottom: 227 },
  { id: 19, file: 'object-19-vending-stack-right.png', x: 1360, y: 87, width: 137, height: 299, visibleBottom: 252 },
  { id: 20, file: 'object-20-hanging-sign-left.png', x: 0, y: 108, width: 140, height: 346, visibleBottom: 304 },
  { id: 21, file: 'object-21-small-stage-statue.png', x: 984, y: 162, width: 102, height: 189, visibleBottom: 135 },
  { id: 22, file: 'object-22-standing-sign-green.png', x: 233, y: 180, width: 176, height: 294, visibleBottom: 268 },
  { id: 23, file: 'object-23-barrier-long.png', x: 755, y: 183, width: 276, height: 174, visibleBottom: 120 },
  { id: 24, file: 'object-24-barrier-short.png', x: 1043, y: 191, width: 134, height: 165, visibleBottom: 111 },
  { id: 25, file: 'object-25-control-post.png', x: 52, y: 283, width: 123, height: 206, visibleBottom: 152 },
  { id: 26, file: 'object-26-trash-bin.png', x: 337, y: 327, width: 183, height: 180, visibleBottom: 133 },
  { id: 27, file: 'object-27-music-sign-right.png', x: 1696, y: 347, width: 168, height: 278, visibleBottom: 224 },
  { id: 28, file: 'object-28-crashed-vehicle.png', x: 0, y: 401, width: 287, height: 303, visibleBottom: 261 },
  { id: 29, file: 'object-29-ground-rock.png', x: 284, y: 412, width: 169, height: 162, visibleBottom: 94 },
  { id: 30, file: 'object-30-edge-sign-right.png', x: 1822, y: 441, width: 98, height: 355, visibleBottom: 316 },
  { id: 31, file: 'object-31-frog-shop.png', x: 1498, y: 490, width: 377, height: 476, visibleBottom: 422 },
  { id: 32, file: 'object-32-blue-creature-pillar.png', x: 324, y: 614, width: 277, height: 341, visibleBottom: 287 },
  { id: 33, file: 'object-33-hanging-sign-bottom-left.png', x: 0, y: 649, width: 325, height: 298, visibleBottom: 244 },
  { id: 34, file: 'object-34-pink-sign-bottom-right.png', x: 1338, y: 660, width: 196, height: 346, visibleBottom: 292 },
  { id: 35, file: 'object-35-edge-figure-right.png', x: 1835, y: 749, width: 85, height: 206, visibleBottom: 152 },
  { id: 36, file: 'object-36-small-canister.png', x: 554, y: 782, width: 133, height: 197, visibleBottom: 143 },
  { id: 37, file: 'object-37-foliage-bank-bottom-left.png', x: 0, y: 847, width: 861, height: 233, visibleBottom: 233 },
  { id: 38, file: 'object-38-foliage-bank-bottom-right.png', x: 1091, y: 847, width: 829, height: 233, visibleBottom: 233 },
  { id: 39, file: 'object-39-low-wall-bottom-center.png', x: 812, y: 994, width: 313, height: 85, visibleBottom: 85 },
];
